# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mafia.proto',
  package='mafia',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmafia.proto\x12\x05mafia\"k\n\x0e\x43onnectRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x1b\n\x13voiceChatServerAddr\x18\x03 \x01(\t\x12\x1b\n\x13voiceChatServerPort\x18\x04 \x01(\x05\"$\n\x14\x43onnectToRoomRequest\x12\x0c\n\x04room\x18\x01 \x01(\t\"\x16\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\":\n\x08Response\x12\x1d\n\x06result\x18\x01 \x01(\x0e\x32\r.mafia.Result\x12\x0f\n\x07message\x18\x02 \x01(\t\"<\n\x07Message\x12 \n\x04type\x18\x01 \x01(\x0e\x32\x12.mafia.MessageType\x12\x0f\n\x07message\x18\x02 \x01(\t*\xa0\x02\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x0e\n\nLoginTaken\x10\x01\x12\x13\n\x0f\x41lreadyLoggedIn\x10\x02\x12\x10\n\x0cUnauthorized\x10\x03\x12\r\n\tNotInRoom\x10\x04\x12\x12\n\x0eGameNotRunning\x10\x05\x12\x17\n\x13\x43\x61ntVoteDuringNight\x10\x06\x12\x16\n\x12\x43\x61ntVoteOnFirstDay\x10\x07\x12\x11\n\rIncorrectName\x10\x08\x12\x15\n\x11\x41lreadyInThisRoom\x10\t\x12\x1a\n\x16\x41lreadyInSomeOtherRoom\x10\n\x12\x0c\n\x08RoomFull\x10\x0b\x12\x11\n\rUnimplemented\x10\x0c\x12\x1c\n\x18\x46\x61iledToLoginToVoiceChat\x10\r*i\n\x0bMessageType\x12\x08\n\x04Info\x10\x00\x12\r\n\tGameEnded\x10\x01\x12\x10\n\x0c\x41ssignedRole\x10\x02\x12\x0c\n\x08\x44\x61yEnded\x10\x03\x12\x0e\n\nNightEnded\x10\x04\x12\x11\n\rYouWereKilled\x10\x05\x32\xf2\x02\n\x0bMafiaServer\x12\x37\n\rConnectClient\x12\x15.mafia.ConnectRequest\x1a\x0f.mafia.Response\x12\x45\n\x15\x43onnectToSpecificRoom\x12\x1b.mafia.ConnectToRoomRequest\x1a\x0f.mafia.Response\x12\'\n\x06\x45ndDay\x12\x0c.mafia.Empty\x1a\x0f.mafia.Response\x12.\n\x0cVoteForMafia\x12\r.mafia.Player\x1a\x0f.mafia.Response\x12,\n\nVoteToKill\x12\r.mafia.Player\x1a\x0f.mafia.Response\x12-\n\x0b\x43heckPlayer\x12\r.mafia.Player\x1a\x0f.mafia.Response\x12-\n\x0bGetMessages\x12\x0c.mafia.Empty\x1a\x0e.mafia.Message0\x01\x62\x06proto3')
)

_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='mafia.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LoginTaken', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AlreadyLoggedIn', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unauthorized', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotInRoom', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GameNotRunning', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CantVoteDuringNight', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CantVoteOnFirstDay', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IncorrectName', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AlreadyInThisRoom', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AlreadyInSomeOtherRoom', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RoomFull', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Unimplemented', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FailedToLoginToVoiceChat', index=13, number=13,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=325,
  serialized_end=613,
)
_sym_db.RegisterEnumDescriptor(_RESULT)

Result = enum_type_wrapper.EnumTypeWrapper(_RESULT)
_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='mafia.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Info', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GameEnded', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AssignedRole', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DayEnded', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NightEnded', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YouWereKilled', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=615,
  serialized_end=720,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
OK = 0
LoginTaken = 1
AlreadyLoggedIn = 2
Unauthorized = 3
NotInRoom = 4
GameNotRunning = 5
CantVoteDuringNight = 6
CantVoteOnFirstDay = 7
IncorrectName = 8
AlreadyInThisRoom = 9
AlreadyInSomeOtherRoom = 10
RoomFull = 11
Unimplemented = 12
FailedToLoginToVoiceChat = 13
Info = 0
GameEnded = 1
AssignedRole = 2
DayEnded = 3
NightEnded = 4
YouWereKilled = 5



_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='mafia.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='mafia.ConnectRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='mafia.ConnectRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voiceChatServerAddr', full_name='mafia.ConnectRequest.voiceChatServerAddr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voiceChatServerPort', full_name='mafia.ConnectRequest.voiceChatServerPort', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=129,
)


_CONNECTTOROOMREQUEST = _descriptor.Descriptor(
  name='ConnectToRoomRequest',
  full_name='mafia.ConnectToRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room', full_name='mafia.ConnectToRoomRequest.room', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=167,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='mafia.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mafia.Player.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=191,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='mafia.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=200,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='mafia.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='mafia.Response.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='mafia.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=260,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='mafia.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='mafia.Message.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='mafia.Message.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=322,
)

_RESPONSE.fields_by_name['result'].enum_type = _RESULT
_MESSAGE.fields_by_name['type'].enum_type = _MESSAGETYPE
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['ConnectToRoomRequest'] = _CONNECTTOROOMREQUEST
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['Result'] = _RESULT
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTREQUEST,
  __module__ = 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.ConnectRequest)
  ))
_sym_db.RegisterMessage(ConnectRequest)

ConnectToRoomRequest = _reflection.GeneratedProtocolMessageType('ConnectToRoomRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTTOROOMREQUEST,
  __module__ = 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.ConnectToRoomRequest)
  ))
_sym_db.RegisterMessage(ConnectToRoomRequest)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.Player)
  ))
_sym_db.RegisterMessage(Player)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.Response)
  ))
_sym_db.RegisterMessage(Response)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'mafia_pb2'
  # @@protoc_insertion_point(class_scope:mafia.Message)
  ))
_sym_db.RegisterMessage(Message)



_MAFIASERVER = _descriptor.ServiceDescriptor(
  name='MafiaServer',
  full_name='mafia.MafiaServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=723,
  serialized_end=1093,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConnectClient',
    full_name='mafia.MafiaServer.ConnectClient',
    index=0,
    containing_service=None,
    input_type=_CONNECTREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConnectToSpecificRoom',
    full_name='mafia.MafiaServer.ConnectToSpecificRoom',
    index=1,
    containing_service=None,
    input_type=_CONNECTTOROOMREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EndDay',
    full_name='mafia.MafiaServer.EndDay',
    index=2,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VoteForMafia',
    full_name='mafia.MafiaServer.VoteForMafia',
    index=3,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='VoteToKill',
    full_name='mafia.MafiaServer.VoteToKill',
    index=4,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CheckPlayer',
    full_name='mafia.MafiaServer.CheckPlayer',
    index=5,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMessages',
    full_name='mafia.MafiaServer.GetMessages',
    index=6,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MAFIASERVER)

DESCRIPTOR.services_by_name['MafiaServer'] = _MAFIASERVER

# @@protoc_insertion_point(module_scope)
